export interface Notifications {
  creationDate: string,
  fromUserImageUrl: string,
  fromUserName: string,
  id: number,
  isSeen: boolean,
  message: string,
  notificationCategoryId: number,
  notificationTypeId: NotificationType,
  typeObjectId: number,
  title: string,
}

export enum NotificationType {
  TASK = 1,
  CANCEL_TASK = 2,
  DELETE_TASK = 3,
  UPDATE_ESTIMATE_TIME = 4,
  TASK_IN_PROGRESS = 5,
  UPDATE_PROGRESS = 6,
  TASK_IS_COMPLETED = 7,
  UPDATE_RATE = 8,
  TASK_WAITING_FOR_APPROVE = 9,
  TASK_APPROVED = 10,
  TASK_REJECTED = 11,
  TASK_FORWARDED = 12,
  JOIN_SPACE_REQUEST = 13,
  REMINDER_HALF = 14,
  REMINDER_ALMOST = 15,
  CREATE_TASK_GROUP_REPORTER = 16,
  END_TIME_FOR_REPEAT = 17,
  TASK_ANNOUNCEMENT = 18,
  VOTE_IS_CREATED = 19,
  VOTE_REMINDER_HALF = 20,
  VOTE_REMINDER_ALMOST = 21,
  VOTE_REMINDER_DONE = 22,
  VOTE_CANCELED = 23,
  VOTE_DELETE = 24,
  KPI_ASSIGN = 41,
  KPI_RATING = 42,

}
