export interface TaskGroupAssignee {
  assigneeId: number,
  assigneeJob: string,
  assigneeName: string,
  assigneeProfilePicture: string,
  endDate: string,
  endedTaskRepeatedCounter: number,
  id: number,
  isOverDue: boolean,
  isRepeated: boolean,
  parentTaskGroupId: number,
  percentage: number,
  priority: number,
  rate: number,
  startDate: string,
  taskGroupId: number,
  taskRepeatedPeriod: number,
  taskStateDate: string,
  taskStateId: number,
  title: string,
  timeLeft: any,
  timeLeftLabel: string,
  bullet: string
}
